openapi: 3.0.0
info:
  version: 1.0.1
  title: voice-library--server-db
servers:
  - url: 'https://demo.identityserver.io/api'
    description: voice-library--server-db API
components:
  securitySchemes:
    identity_server_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://demo.identityserver.io/connect/authorize'
          scopes:
            api: api
  schemas:
    db-id:
      type: string
      minLength: 2
      maxLength: 20
      pattern: '^i[0-9]+$'
      example: i12345
    sa-id-array:
      type: object
      required:
        - said__SentenceAudioId
      properties:
        said__SentenceAudioId:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/db-id'
    sa-info:
      type: object
      required:
        - b64__Base64
        - ms__Millisecond
        - said__SentenceAudioId
        - tp__Type
      properties:
        b64__Base64:
          type: object
          required:
            - b64__Base64
            - cnt__Count
          properties:
            b64__Base64:
              type: string
              example: T2dnUwACAAAAAAAAAACQKGFtAAAAANN4JuQBHgF2b3JiaXMAAAAAASJWAAAA...
            cnt__Count:
              type: integer
        ms__Millisecond:
          type: integer
        said__SentenceAudioId:
          $ref: '#/components/schemas/db-id'
        tp__Type:
          enum:
            - ogg
paths:
  /fn__voice.check_available_voice_sa_ids_ogg:
    post:
      summary: Check available voice sa ids ogg.
      operationId: VL-09EE21
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sa-id-array'
      responses:
        '200':
          description: Ok.
          content:
            application/json:
              schema:
                type: object
                required:
                  - dt__Data
                properties:
                  dt__Data:
                    type: object
                    required:
                      - said__SentenceAudioId
                    properties:
                      said__SentenceAudioId:
                        type: object
                        required:
                          - abl__Available
                          - chk__Check
                        properties:
                          abl__Available:
                            type: array
                            items:
                              oneOf:
                                - $ref: '#/components/schemas/db-id'
                          chk__Check:
                            type: array
                            items:
                              oneOf:
                                - $ref: '#/components/schemas/db-id'
  /fn__voice.read_sentence_ogg_b64:
    post:
      summary: Read voice sa ogg.
      operationId: VL-2EDC0C
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sa-id-array'
      responses:
        '200':
          description: Ok.
          content:
            application/json:
              schema:
                type: object
                required:
                  - dt__Data
                properties:
                  dt__Data:
                    type: object
                    required:
                      - sa__SentenceAudio
                    properties:
                      sa__SentenceAudio:
                        type: object
                        description: key for said.
                        additionalProperties:
                          $ref: '#/components/schemas/sa-info'
